### ISSUE TITLE
[Unexpected Behavior] Fatal Error

### ISSUE THREAD

**Issue by xTHECONNORx** [Nepumi/MusicMemories#2]
Well, when I was playing your SM 5.3 Theme, it was behaving as normal when all of a sudden...

![](https://user-images.githubusercontent.com/81449746/112703667-04461c00-8e55-11eb-9f8d-92be70e17b1b.png)

When I clicked abort, I got this:

![](https://user-images.githubusercontent.com/81449746/112703688-16c05580-8e55-11eb-9b1f-64e51f4b7e4b.png)

**Comment by Nepumi-Jr** [comment]
Thanks for reporting this Fatal error
I just fix recently and upload it to this repository.

Like I said in README.md _"⚠️This theme is still in development.⚠️"._ 
I know that there is a lot of bug or issue in my theme.
But during this time I have some big project to do (not this one :( )  so I don't have time to fix all Theme's bugs now.

If you found an issue feel free to let me know in this repository (this page).
Not [Outfox themselve](https://github.com/TeamRizu/OutFox/) Because This theme is like the **third party of SM 5.3** _not original or pure SM5.3_
